const mockOrdnanceSurveyResponse = {
  header: {
    uri: 'testuri',
    query: 'postcode=SW1A2AA',
    offset: 0,
    totalresults: 1,
    format: 'JSON',
    dataset: 'DPA',
    lr: 'EN,CY',
    maxresults: 100,
    epoch: '103',
    lastupdate: '2023-09-08',
    output_srs: 'EPSG:27700',
  },
  results: [
    {
      DPA: {
        UPRN: '1',
        UDPRN: '2',
        ADDRESS: 'PRIME MINISTER & FIRST LORD OF THE TREASURY, 10, DOWNING STREET, LONDON, SW1A 2AA',
        ORGANISATION_NAME: '',
        BUILDING_NUMBER: '',
        SUB_BUILDING_NAME: 'MOCK SUB BUILDING NAME',
        BUILDING_NAME: '',
        THOROUGHFARE_NAME: 'DOWNING STREET',
        POST_TOWN: 'LONDON',
        POSTCODE: 'SW1A 2AA',
        RPC: '2',
        X_COORDINATE: 530047.0,
        Y_COORDINATE: 179951.0,
        STATUS: 'APPROVED',
        LOGICAL_STATUS_CODE: '1',
        CLASSIFICATION_CODE: 'RD04',
        CLASSIFICATION_CODE_DESCRIPTION: 'Terraced',
        LOCAL_CUSTODIAN_CODE: 5990,
        LOCAL_CUSTODIAN_CODE_DESCRIPTION: 'CITY OF WESTMINSTER',
        COUNTRY_CODE: 'E',
        COUNTRY_CODE_DESCRIPTION: 'This record is within England',
        POSTAL_ADDRESS_CODE: 'D',
        POSTAL_ADDRESS_CODE_DESCRIPTION: 'A record which is linked to PAF',
        BLPU_STATE_CODE: '2',
        BLPU_STATE_CODE_DESCRIPTION: 'In use',
        TOPOGRAPHY_LAYER_TOID: 'osgb1000005572568',
        LAST_UPDATE_DATE: '24/11/2021',
        ENTRY_DATE: '19/03/2001',
        BLPU_STATE_DATE: '19/03/2001',
        LANGUAGE: 'EN',
        MATCH: 1.0,
        MATCH_DESCRIPTION: 'EXACT',
        DELIVERY_POINT_SUFFIX: '1A',
      },
    },
    {
      DPA: {
        UPRN: '1',
        UDPRN: '2',
        ADDRESS: 'PRIME MINISTER & FIRST LORD OF THE TREASURY, 11, DOWNING STREET, LONDON, SW1A 2AA',
        ORGANISATION_NAME: '',
        BUILDING_NUMBER: '',
        SUB_BUILDING_NAME: '',
        BUILDING_NAME: 'EXAMPLE BUILDING NAME',
        THOROUGHFARE_NAME: 'DOWNING STREET',
        POST_TOWN: 'LONDON',
        POSTCODE: 'SW1A 2AA',
        RPC: '2',
        X_COORDINATE: 530047.0,
        Y_COORDINATE: 179951.0,
        STATUS: 'APPROVED',
        LOGICAL_STATUS_CODE: '1',
        CLASSIFICATION_CODE: 'RD04',
        CLASSIFICATION_CODE_DESCRIPTION: 'Terraced',
        LOCAL_CUSTODIAN_CODE: 5990,
        LOCAL_CUSTODIAN_CODE_DESCRIPTION: 'CITY OF WESTMINSTER',
        COUNTRY_CODE: 'E',
        COUNTRY_CODE_DESCRIPTION: 'This record is within England',
        POSTAL_ADDRESS_CODE: 'D',
        POSTAL_ADDRESS_CODE_DESCRIPTION: 'A record which is linked to PAF',
        BLPU_STATE_CODE: '2',
        BLPU_STATE_CODE_DESCRIPTION: 'In use',
        TOPOGRAPHY_LAYER_TOID: 'osgb1000005572568',
        LAST_UPDATE_DATE: '24/11/2021',
        ENTRY_DATE: '19/03/2001',
        BLPU_STATE_DATE: '19/03/2001',
        LANGUAGE: 'EN',
        MATCH: 1.0,
        MATCH_DESCRIPTION: 'EXACT',
        DELIVERY_POINT_SUFFIX: '1A',
      },
    },
    {
      DPA: {
        UPRN: '1',
        UDPRN: '2',
        ADDRESS: 'PRIME MINISTER & FIRST LORD OF THE TREASURY, 10, DOWNING STREET, LONDON, SW1A 2AA',
        ORGANISATION_NAME: 'PRIME MINISTER & FIRST LORD OF THE TREASURY',
        BUILDING_NUMBER: '',
        SUB_BUILDING_NAME: '',
        BUILDING_NAME: '',
        THOROUGHFARE_NAME: 'DOWNING STREET',
        POST_TOWN: 'LONDON',
        POSTCODE: 'SW1A 2AA',
        RPC: '2',
        X_COORDINATE: 530047.0,
        Y_COORDINATE: 179951.0,
        STATUS: 'APPROVED',
        LOGICAL_STATUS_CODE: '1',
        CLASSIFICATION_CODE: 'RD04',
        CLASSIFICATION_CODE_DESCRIPTION: 'Terraced',
        LOCAL_CUSTODIAN_CODE: 5990,
        LOCAL_CUSTODIAN_CODE_DESCRIPTION: 'CITY OF WESTMINSTER',
        COUNTRY_CODE: 'E',
        COUNTRY_CODE_DESCRIPTION: 'This record is within England',
        POSTAL_ADDRESS_CODE: 'D',
        POSTAL_ADDRESS_CODE_DESCRIPTION: 'A record which is linked to PAF',
        BLPU_STATE_CODE: '2',
        BLPU_STATE_CODE_DESCRIPTION: 'In use',
        TOPOGRAPHY_LAYER_TOID: 'osgb1000005572568',
        LAST_UPDATE_DATE: '24/11/2021',
        ENTRY_DATE: '19/03/2001',
        BLPU_STATE_DATE: '19/03/2001',
        LANGUAGE: 'EN',
        MATCH: 1.0,
        MATCH_DESCRIPTION: 'EXACT',
        DELIVERY_POINT_SUFFIX: '1A',
      },
    },
    {
      DPA: {
        UPRN: '10033548201',
        UDPRN: '23748017',
        ADDRESS: 'H M TREASURY, 1, HORSE GUARDS ROAD, LONDON, SW1A 2HQ',
        BUILDING_NUMBER: '1',
        ORGANISATION_NAME: '',
        SUB_BUILDING_NAME: '',
        BUILDING_NAME: '',
        THOROUGHFARE_NAME: 'HORSE GUARDS ROAD',
        POST_TOWN: 'LONDON',
        POSTCODE: 'SW1A 2HQ',
        RPC: '2',
        X_COORDINATE: 529944,
        Y_COORDINATE: 179754,
        STATUS: 'APPROVED',
        LOGICAL_STATUS_CODE: '1',
        CLASSIFICATION_CODE: 'CO01',
        CLASSIFICATION_CODE_DESCRIPTION: 'Office / Work Studio',
        LOCAL_CUSTODIAN_CODE: 5990,
        LOCAL_CUSTODIAN_CODE_DESCRIPTION: 'CITY OF WESTMINSTER',
        COUNTRY_CODE: 'E',
        COUNTRY_CODE_DESCRIPTION: 'This record is within England',
        POSTAL_ADDRESS_CODE: 'D',
        POSTAL_ADDRESS_CODE_DESCRIPTION: 'A record which is linked to PAF',
        BLPU_STATE_CODE: '2',
        BLPU_STATE_CODE_DESCRIPTION: 'In use',
        TOPOGRAPHY_LAYER_TOID: 'osgb1000042216423',
        WARD_CODE: 'E05013806',
        LAST_UPDATE_DATE: '12/11/2018',
        ENTRY_DATE: '27/04/2003',
        BLPU_STATE_DATE: '27/04/2003',
        LANGUAGE: 'EN',
        MATCH: 1,
        MATCH_DESCRIPTION: 'EXACT',
        DELIVERY_POINT_SUFFIX: '1A',
      },
    },
  ],
};

export default mockOrdnanceSurveyResponse;
