const FIELD_IDS = require('./field-ids');
const ROUTES = require('./routes');
const { FIELDS } = require('../content-strings');

const {
  VALID_COMPANY_BASE,
  VALID_BUYER_BASE,
  TRIED_PRIVATE_COVER,
  UK_CONTENT_PERCENTAGE,
  AMOUNT,
  CURRENCY,
  PRE_CREDIT_PERIOD,
  CREDIT_PERIOD,
  POLICY_TYPE,
  POLICY_LENGTH,
} = FIELD_IDS;

const FIELD_GROUPS = {
  COMPANY_DETAILS: {
    FIELDS: [
      {
        ID: VALID_COMPANY_BASE,
        ...FIELDS[VALID_COMPANY_BASE],
        CHANGE_ROUTE: ROUTES.COMPANY_BASED_CHANGE,
      },
    ],
  },
  EXPORT_DETAILS: {
    FIELDS: [
      {
        ID: VALID_BUYER_BASE,
        ...FIELDS[VALID_BUYER_BASE],
        CHANGE_ROUTE: ROUTES.BUYER_BASED_CHANGE,
      },
      {
        ID: TRIED_PRIVATE_COVER,
        ...FIELDS[TRIED_PRIVATE_COVER],
        CHANGE_ROUTE: ROUTES.TRIED_TO_OBTAIN_COVER_CHANGE,
      },
      {
        ID: UK_CONTENT_PERCENTAGE,
        ...FIELDS[UK_CONTENT_PERCENTAGE],
        CHANGE_ROUTE: ROUTES.UK_CONTENT_PERCENTAGE_CHANGE,
      },
    ],
  },
  DEAL_DETAILS: {
    FIELDS: [
      {
        ID: AMOUNT,
        ...FIELDS[AMOUNT],
        CHANGE_ROUTE: ROUTES.TELL_US_ABOUT_YOUR_DEAL_CHANGE,
      },
      {
        ID: CURRENCY,
        ...FIELDS[CURRENCY],
        CHANGE_ROUTE: ROUTES.TELL_US_ABOUT_YOUR_DEAL_CHANGE,
      },
      {
        ID: PRE_CREDIT_PERIOD,
        ...FIELDS[PRE_CREDIT_PERIOD],
        CHANGE_ROUTE: ROUTES.TELL_US_ABOUT_YOUR_DEAL_CHANGE,
      },
      {
        ID: CREDIT_PERIOD,
        ...FIELDS[CREDIT_PERIOD],
        CHANGE_ROUTE: ROUTES.TELL_US_ABOUT_YOUR_DEAL_CHANGE,
      },
      {
        ID: POLICY_TYPE,
        ...FIELDS[POLICY_TYPE],
        CHANGE_ROUTE: ROUTES.TELL_US_ABOUT_YOUR_DEAL_CHANGE,
      },
      {
        ID: POLICY_LENGTH,
        ...FIELDS[POLICY_LENGTH],
        CHANGE_ROUTE: ROUTES.TELL_US_ABOUT_YOUR_DEAL_CHANGE,
      },
    ],
  },
};

module.exports = FIELD_GROUPS;
