import {
  createAnAccount,
  deleteAnAccount,
  verifyAccountEmailAddress,
  sendEmailConfirmEmailAddress,
  accountSignIn,
  accountSignInSendNewCode,
  verifyAccountSignInCode,
  addAndGetOTP,
  accountPasswordReset,
  sendEmailPasswordResetLink,
  sendEmailReactivateAccountLink,
  createAnApplication,
  deleteApplicationByReferenceNumber,
  updateCompanyAndCompanyAddress,
  submitApplication,
  createFeedbackAndSendEmail,
  verifyAccountReactivationToken,
} from './mutations';
import {
  getAccountPasswordResetToken,
  getApimCisCountries,
  getCompaniesHouseInformation,
  getOrdnanceSurveyAddress,
  verifyAccountPasswordResetToken,
} from './queries';

/**
 * customResolvers
 * Custom resolvers to add to the GraphQL API/schema automatically generated by KeystoneJS
 * Note: Any new resolvers need to be added to ./type-defs.ts.
 * Otherwise, the resolver will not be added.
 * @returns {Object} Object with custom queries and mutations
 */
const customResolvers = {
  Mutation: {
    createAnAccount,
    deleteAnAccount,
    accountSignIn,
    accountSignInSendNewCode,
    verifyAccountEmailAddress,
    sendEmailConfirmEmailAddress,
    verifyAccountSignInCode,
    addAndGetOTP,
    accountPasswordReset,
    sendEmailPasswordResetLink,
    sendEmailReactivateAccountLink,
    createAnApplication,
    deleteApplicationByReferenceNumber,
    updateCompanyAndCompanyAddress,
    submitApplication,
    createFeedbackAndSendEmail,
    verifyAccountReactivationToken,
  },
  Query: {
    getAccountPasswordResetToken,
    getApimCisCountries,
    getCompaniesHouseInformation,
    getOrdnanceSurveyAddress,
    verifyAccountPasswordResetToken,
  },
};

export default customResolvers;
