# EXIP Git Hub Actions
#####################################
# Automatic dependencies updates
# for the following services:
# 1. NPM
# 2. Docker
# 3. GHA

version: 2
updates:
  # Root package-*.json files
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '17:15'
    labels:
      - 'chore'
    ignore:
      - dependency-name: "@keystone-6/core"
        versions: [">=6.0.0"]
      - dependency-name: "@keystone-6/auth"
        versions: [">=8.0.0"]
      - dependency-name: "@keystone-6/fields-document"
        versions: [">=9.0.0"]
      - dependency-name: "@typescript-eslint/parser"
        versions: [">=8.0.0"]
      - dependency-name: "@typescript-eslint/eslint-plugin"
        versions: [">=8.0.0"]
      - dependency-name: "graphql"
        versions: [">=16.0.0"]
      - dependency-name: "eslint"
        versions: [">=9.0.0"]
      - dependency-name: "eslint-plugin-cypress"
        versions: [">=4.0.0"]
      - dependency-name: "eslint-plugin-prettier"
        versions: [">=5.0.0"]
      - dependency-name: "prettier"
        versions: [">=3.0.0"]
    groups:
      npm-packages:
        patterns:
          - '*'  

  # `API` package-*.json files
  - package-ecosystem: 'npm'
    directory: '/src/api'
    schedule:
      interval: 'daily'
      time: '17:15'
    labels:
      - 'chore'
    ignore:
      - dependency-name: "@keystone-6/core"
        versions: [">=6.0.0"]
      - dependency-name: "@keystone-6/auth"
        versions: [">=8.0.0"]
      - dependency-name: "@keystone-6/fields-document"
        versions: [">=9.0.0"]
      - dependency-name: "@typescript-eslint/eslint-plugin"
        versions: [">=8.0.0"]
      - dependency-name: "@typescript-eslint/parser"
        versions: [">=8.0.0"]
      - dependency-name: "eslint"
        versions: [">=9.0.0"]
      - dependency-name: "eslint-plugin-cypress"
        versions: [">=4.0.0"]
      - dependency-name: "eslint-plugin-prettier"
        versions: [">=5.0.0"]
      - dependency-name: "prettier"
        versions: [">=3.0.0"]
    groups:
      npm-packages:
        patterns:
          - '*'

  # `UI` package-*.json files
  - package-ecosystem: 'npm'
    directory: '/src/ui'
    schedule:
      interval: 'daily'
      time: '17:15'
    labels:
      - 'chore'
    ignore:
      - dependency-name: "graphql"
        versions: [">=16.0.0"]
      - dependency-name: "@typescript-eslint/eslint-plugin"
        versions: [">=8.0.0"]
      - dependency-name: "@typescript-eslint/parser"
        versions: [">=8.0.0"]
      - dependency-name: "eslint"
        versions: [">=9.0.0"]
      - dependency-name: "eslint-plugin-cypress"
        versions: [">=4.0.0"]
      - dependency-name: "eslint-plugin-prettier"
        versions: [">=5.0.0"]
      - dependency-name: "prettier"
        versions: [">=3.0.0"]
    groups:
      npm-packages:
        patterns:
          - '*'

  # `generate-exip-pricing-grid` package-*.json files
  - package-ecosystem: 'npm'
    directory: '/generate-exip-pricing-grid'
    schedule:
      interval: 'daily'
      time: '17:15'
    labels:
      - 'chore'
    groups:
      npm-packages:
        patterns:
          - '*'

  # `API` Dockerfile
  - package-ecosystem: 'docker'
    directory: '/src/api'
    schedule:
      interval: 'daily'
      time: '17:15'
    labels:
      - 'chore'
    groups:
      docker-packages:
        patterns:
          - '*'

  # `UI` Dockerfile
  - package-ecosystem: 'docker'
    directory: '/src/ui'
    schedule:
      interval: 'daily'
      time: '17:15'
    labels:
      - 'chore'
    groups:
      docker-packages:
        patterns:
          - '*'

  # Git Hub Actions
  #  Set the directory to `/` for
  # .github/workflows GHA files
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '17:15'
    labels:
      - 'chore'
    groups:
      github-actions:
        patterns:
          - '*'
