const EXPORTER_BUSINESS_ROOT = '/your-business';
const COMPANY_DETAILS_ROOT = `${EXPORTER_BUSINESS_ROOT}/company-details`;
const ALTERNATIVE_TRADING_ADDRESS_ROOT = `${EXPORTER_BUSINESS_ROOT}/alternative-trading-address`;
const NATURE_OF_BUSINESS_ROOT = 'nature-of-business';
const TURNOVER_ROOT = 'turnover';
const CREDIT_CONTROL_ROOT = `${EXPORTER_BUSINESS_ROOT}/credit-control`;
const BROKER_ROOT = 'broker';
const CHECK_YOUR_ANSWERS = 'check-your-answers';

export const EXPORTER_BUSINESS = {
  ROOT: EXPORTER_BUSINESS_ROOT,
  COMPANY_DETAILS_ROOT,
  COMPANY_DETAILS: COMPANY_DETAILS_ROOT,
  COMPANY_DETAILS_CHANGE: `${COMPANY_DETAILS_ROOT}/change`,
  COMPANY_DETAILS_CHECK_AND_CHANGE: `${COMPANY_DETAILS_ROOT}/check-and-change`,
  ALTERNATIVE_TRADING_ADDRESS_ROOT,
  NATURE_OF_BUSINESS: `${EXPORTER_BUSINESS_ROOT}/${NATURE_OF_BUSINESS_ROOT}`,
  NATURE_OF_BUSINESS_CHANGE: `${EXPORTER_BUSINESS_ROOT}/${NATURE_OF_BUSINESS_ROOT}/change`,
  NATURE_OF_BUSINESS_CHECK_AND_CHANGE: `${EXPORTER_BUSINESS_ROOT}/${NATURE_OF_BUSINESS_ROOT}/check-and-change`,
  TURNOVER: `${EXPORTER_BUSINESS_ROOT}/${TURNOVER_ROOT}`,
  TURNOVER_CHANGE: `${EXPORTER_BUSINESS_ROOT}/${TURNOVER_ROOT}/change`,
  TURNOVER_CHECK_AND_CHANGE: `${EXPORTER_BUSINESS_ROOT}/${TURNOVER_ROOT}/check-and-change`,
  CREDIT_CONTROL: CREDIT_CONTROL_ROOT,
  BROKER: `${EXPORTER_BUSINESS_ROOT}/${BROKER_ROOT}`,
  BROKER_CHANGE: `${EXPORTER_BUSINESS_ROOT}/${BROKER_ROOT}/change`,
  BROKER_CHECK_AND_CHANGE: `${EXPORTER_BUSINESS_ROOT}/${BROKER_ROOT}/check-and-change`,
  CHECK_YOUR_ANSWERS: `${EXPORTER_BUSINESS_ROOT}/${CHECK_YOUR_ANSWERS}`,
};
