const EXPORTER_BUSINESS_ROOT = '/your-business';
const COMPANY_DETAILS_ROOT = 'company-details';
const NATURE_OF_BUSINESS_ROOT = 'nature-of-business';
const TURNOVER_ROOT = 'turnover';
const BROKER_ROOT = 'broker';
const CHECK_YOUR_ANSWERS = 'check-your-answers';

export const EXPORTER_BUSINESS = {
  ROOT: EXPORTER_BUSINESS_ROOT,
  COMPANY_DETAILS: `${EXPORTER_BUSINESS_ROOT}/${COMPANY_DETAILS_ROOT}`,
  COMPANIES_HOUSE_UNAVAILABLE: `${EXPORTER_BUSINESS_ROOT}/company-details-unavailable`,
  COMPANY_DETAILS_CHANGE: `${EXPORTER_BUSINESS_ROOT}/${COMPANY_DETAILS_ROOT}/change`,
  COMPANY_DETAILS_CHECK_AND_CHANGE: `${EXPORTER_BUSINESS_ROOT}/${COMPANY_DETAILS_ROOT}/check-and-change`,
  COMPANY_HOUSE_SEARCH: `${EXPORTER_BUSINESS_ROOT}/${COMPANY_DETAILS_ROOT}/companies-house-search`,
  NATURE_OF_BUSINESS: `${EXPORTER_BUSINESS_ROOT}/${NATURE_OF_BUSINESS_ROOT}`,
  NATURE_OF_BUSINESS_CHANGE: `${EXPORTER_BUSINESS_ROOT}/${NATURE_OF_BUSINESS_ROOT}/change`,
  NATURE_OF_BUSINESS_CHECK_AND_CHANGE: `${EXPORTER_BUSINESS_ROOT}/${NATURE_OF_BUSINESS_ROOT}/check-and-change`,
  TURNOVER: `${EXPORTER_BUSINESS_ROOT}/${TURNOVER_ROOT}`,
  TURNOVER_CHANGE: `${EXPORTER_BUSINESS_ROOT}/${TURNOVER_ROOT}/change`,
  TURNOVER_CHECK_AND_CHANGE: `${EXPORTER_BUSINESS_ROOT}/${TURNOVER_ROOT}/check-and-change`,
  BROKER: `${EXPORTER_BUSINESS_ROOT}/${BROKER_ROOT}`,
  BROKER_CHANGE: `${EXPORTER_BUSINESS_ROOT}/${BROKER_ROOT}/change`,
  BROKER_CHECK_AND_CHANGE: `${EXPORTER_BUSINESS_ROOT}/${BROKER_ROOT}/check-and-change`,
  CHECK_YOUR_ANSWERS: `${EXPORTER_BUSINESS_ROOT}/${CHECK_YOUR_ANSWERS}`,
};
