const ROOT = '/insurance-policy';
const BROKER_ROOT = `${ROOT}/broker`;

export const POLICY = {
  ROOT,
  TYPE_OF_POLICY: `${ROOT}/type-of-policy`,
  TYPE_OF_POLICY_SAVE_AND_BACK: `${ROOT}/type-of-policy/save-and-go-back`,
  TYPE_OF_POLICY_CHANGE: `${ROOT}/type-of-policy/change`,
  TYPE_OF_POLICY_CHECK_AND_CHANGE: `${ROOT}/type-of-policy/check-and-change`,
  SINGLE_CONTRACT_POLICY: `${ROOT}/single-contract-policy`,
  SINGLE_CONTRACT_POLICY_SAVE_AND_BACK: `${ROOT}/single-contract-policy/save-and-go-back`,
  SINGLE_CONTRACT_POLICY_CHANGE: `${ROOT}/single-contract-policy/change`,
  SINGLE_CONTRACT_POLICY_CHECK_AND_CHANGE: `${ROOT}/single-contract-policy/check-and-change`,
  SINGLE_CONTRACT_POLICY_TOTAL_CONTRACT_VALUE: `${ROOT}/single-contract-policy/total-contract-value`,
  SINGLE_CONTRACT_POLICY_TOTAL_CONTRACT_VALUE_SAVE_AND_BACK: `${ROOT}/single-contract-policy/total-contract-value/save-and-go-back`,
  SINGLE_CONTRACT_POLICY_TOTAL_CONTRACT_VALUE_CHANGE: `${ROOT}/single-contract-policy/total-contract-value/change`,
  SINGLE_CONTRACT_POLICY_TOTAL_CONTRACT_VALUE_CHECK_AND_CHANGE: `${ROOT}/single-contract-policy/total-contract-value/check-and-change`,
  MULTIPLE_CONTRACT_POLICY: `${ROOT}/multi-contract-policy`,
  MULTIPLE_CONTRACT_POLICY_SAVE_AND_BACK: `${ROOT}/multi-contract-policy/save-and-go-back`,
  MULTIPLE_CONTRACT_POLICY_CHANGE: `${ROOT}/multi-contract-policy/change`,
  MULTIPLE_CONTRACT_POLICY_CHECK_AND_CHANGE: `${ROOT}/multi-contract-policy/check-and-change`,
  MULTIPLE_CONTRACT_POLICY_EXPORT_VALUE: `${ROOT}/multi-contract-policy/export-value`,
  MULTIPLE_CONTRACT_POLICY_EXPORT_VALUE_SAVE_AND_BACK: `${ROOT}/multi-contract-policy/export-value/save-and-go-back`,
  NAME_ON_POLICY: `${ROOT}/name-on-policy`,
  NAME_ON_POLICY_SAVE_AND_BACK: `${ROOT}/name-on-policy/save-and-go-back`,
  NAME_ON_POLICY_CHANGE: `${ROOT}/name-on-policy/change`,
  NAME_ON_POLICY_CHECK_AND_CHANGE: `${ROOT}/name-on-policy/check-and-change`,
  DIFFERENT_NAME_ON_POLICY: `${ROOT}/different-name-on-policy`,
  DIFFERENT_NAME_ON_POLICY_SAVE_AND_BACK: `${ROOT}/different-name-on-policy/save-and-go-back`,
  DIFFERENT_NAME_ON_POLICY_CHANGE: `${ROOT}/different-name-on-policy/change`,
  DIFFERENT_NAME_ON_POLICY_CHECK_AND_CHANGE: `${ROOT}/different-name-on-policy/check-and-change`,
  PRE_CREDIT_PERIOD: `${ROOT}/pre-credit-period`,
  PRE_CREDIT_PERIOD_SAVE_AND_BACK: `${ROOT}/pre-credit-period/save-and-go-back`,
  BROKER_ROOT,
  BROKER_SAVE_AND_BACK: `${BROKER_ROOT}/save-and-back`,
  BROKER_CHANGE: `${BROKER_ROOT}/change`,
  BROKER_CHECK_AND_CHANGE: `${BROKER_ROOT}/check-and-change`,
  CHECK_YOUR_ANSWERS: `${ROOT}/check-your-answers`,
};
