const ROOT = '/insurance-policy';
const BROKER_ROOT = `${ROOT}/broker`;
const BROKER_DETAILS_ROOT = `${ROOT}/broker-details`;
const BROKER_CONFIRM_ADDRESS_ROOT = `${ROOT}/broker-confirm-address`;

export const POLICY = {
  ROOT,
  TYPE_OF_POLICY: `${ROOT}/type-of-policy`,
  TYPE_OF_POLICY_SAVE_AND_BACK: `${ROOT}/type-of-policy/save-and-go-back`,
  TYPE_OF_POLICY_CHANGE: `${ROOT}/type-of-policy/change`,
  TYPE_OF_POLICY_CHECK_AND_CHANGE: `${ROOT}/type-of-policy/check-and-change`,
  SINGLE_CONTRACT_POLICY: `${ROOT}/single-contract-policy`,
  SINGLE_CONTRACT_POLICY_SAVE_AND_BACK: `${ROOT}/single-contract-policy/save-and-go-back`,
  SINGLE_CONTRACT_POLICY_CHANGE: `${ROOT}/single-contract-policy/change`,
  SINGLE_CONTRACT_POLICY_CHECK_AND_CHANGE: `${ROOT}/single-contract-policy/check-and-change`,
  SINGLE_CONTRACT_POLICY_TOTAL_CONTRACT_VALUE: `${ROOT}/single-contract-policy/total-contract-value`,
  SINGLE_CONTRACT_POLICY_TOTAL_CONTRACT_VALUE_SAVE_AND_BACK: `${ROOT}/single-contract-policy/total-contract-value/save-and-go-back`,
  SINGLE_CONTRACT_POLICY_TOTAL_CONTRACT_VALUE_CHANGE: `${ROOT}/single-contract-policy/total-contract-value/change`,
  SINGLE_CONTRACT_POLICY_TOTAL_CONTRACT_VALUE_CHECK_AND_CHANGE: `${ROOT}/single-contract-policy/total-contract-value/check-and-change`,
  MULTIPLE_CONTRACT_POLICY: `${ROOT}/multiple-contract-policy`,
  MULTIPLE_CONTRACT_POLICY_SAVE_AND_BACK: `${ROOT}/multiple-contract-policy/save-and-go-back`,
  MULTIPLE_CONTRACT_POLICY_CHANGE: `${ROOT}/multiple-contract-policy/change`,
  MULTIPLE_CONTRACT_POLICY_CHECK_AND_CHANGE: `${ROOT}/multiple-contract-policy/check-and-change`,
  MULTIPLE_CONTRACT_POLICY_EXPORT_VALUE: `${ROOT}/multiple-contract-policy/export-value`,
  MULTIPLE_CONTRACT_POLICY_EXPORT_VALUE_SAVE_AND_BACK: `${ROOT}/multiple-contract-policy/export-value/save-and-go-back`,
  MULTIPLE_CONTRACT_POLICY_EXPORT_VALUE_CHANGE: `${ROOT}/multiple-contract-policy/export-value/change`,
  MULTIPLE_CONTRACT_POLICY_EXPORT_VALUE_CHECK_AND_CHANGE: `${ROOT}/multiple-contract-policy/export-value/check-and-change`,
  NAME_ON_POLICY: `${ROOT}/name-on-policy`,
  NAME_ON_POLICY_SAVE_AND_BACK: `${ROOT}/name-on-policy/save-and-go-back`,
  NAME_ON_POLICY_CHANGE: `${ROOT}/name-on-policy/change`,
  NAME_ON_POLICY_CHECK_AND_CHANGE: `${ROOT}/name-on-policy/check-and-change`,
  DIFFERENT_NAME_ON_POLICY: `${ROOT}/different-name-on-policy`,
  DIFFERENT_NAME_ON_POLICY_SAVE_AND_BACK: `${ROOT}/different-name-on-policy/save-and-go-back`,
  DIFFERENT_NAME_ON_POLICY_CHANGE: `${ROOT}/different-name-on-policy/change`,
  DIFFERENT_NAME_ON_POLICY_CHECK_AND_CHANGE: `${ROOT}/different-name-on-policy/check-and-change`,
  PRE_CREDIT_PERIOD: `${ROOT}/pre-credit-period`,
  PRE_CREDIT_PERIOD_SAVE_AND_BACK: `${ROOT}/pre-credit-period/save-and-go-back`,
  PRE_CREDIT_PERIOD_CHANGE: `${ROOT}/pre-credit-period/change`,
  PRE_CREDIT_PERIOD_CHECK_AND_CHANGE: `${ROOT}/pre-credit-period/check-and-change`,
  ANOTHER_COMPANY: `${ROOT}/another-company`,
  ANOTHER_COMPANY_SAVE_AND_BACK: `${ROOT}/another-company/save-and-go-back`,
  OTHER_COMPANY_DETAILS: `${ROOT}/other-company-details`,
  BROKER_ROOT,
  BROKER_SAVE_AND_BACK: `${BROKER_ROOT}/save-and-back`,
  BROKER_CHANGE: `${BROKER_ROOT}/change`,
  BROKER_CHECK_AND_CHANGE: `${BROKER_ROOT}/check-and-change`,
  BROKER_DETAILS_ROOT,
  BROKER_CONFIRM_ADDRESS_ROOT,
  CHECK_YOUR_ANSWERS: `${ROOT}/check-your-answers`,
};
