const YOUR_BUYER_ROOT = '/your-buyer';
const COMPANY_OR_ORGANISATION_ROOT = `${YOUR_BUYER_ROOT}/buyer-company-organisation`;
const CONNECTION_WITH_BUYER_ROOT = `${YOUR_BUYER_ROOT}/connection-with-the-buyer`;
const WORKING_WITH_BUYER_ROOT = `${YOUR_BUYER_ROOT}/working-with-buyer`;
const CHECK_YOUR_ANSWERS = `${YOUR_BUYER_ROOT}/check-your-answers`;

export const YOUR_BUYER = {
  ROOT: YOUR_BUYER_ROOT,
  COMPANY_OR_ORGANISATION: COMPANY_OR_ORGANISATION_ROOT,
  COMPANY_OR_ORGANISATION_CHANGE: `${COMPANY_OR_ORGANISATION_ROOT}/change`,
  COMPANY_OR_ORGANISATION_CHECK_AND_CHANGE: `${COMPANY_OR_ORGANISATION_ROOT}/check-and-change`,
  CONNECTION_WITH_BUYER: CONNECTION_WITH_BUYER_ROOT,
  WORKING_WITH_BUYER: WORKING_WITH_BUYER_ROOT,
  WORKING_WITH_BUYER_CHANGE: `${WORKING_WITH_BUYER_ROOT}/change`,
  WORKING_WITH_BUYER_CHECK_AND_CHANGE: `${WORKING_WITH_BUYER_ROOT}/check-and-change`,
  WORKING_WITH_BUYER_SAVE_AND_BACK: `${WORKING_WITH_BUYER_ROOT}/save-and-back`,
  CHECK_YOUR_ANSWERS,
};
