import POLICY_ROOT from './root';

const ROOT = `${POLICY_ROOT}/loss-payee`;
const LOSS_PAYEE_DETAILS_ROOT = `${POLICY_ROOT}/loss-payee-details`;
const LOSS_PAYEE_FINANCIAL_UK_ROOT = `${POLICY_ROOT}/loss-payee-bank-details`;
const LOSS_PAYEE_FINANCIAL_INTERNATIONAL_ROOT = `${ROOT}/loss-payee-international-bank-details`;

const LOSS_PAYEE_ROUTES = {
  LOSS_PAYEE_ROOT: ROOT,
  LOSS_PAYEE_SAVE_AND_BACK: `${ROOT}/save-and-back`,
  LOSS_PAYEE_CHANGE: `${ROOT}/change`,
  LOSS_PAYEE_CHECK_AND_CHANGE: `${ROOT}/check-and-change`,
  LOSS_PAYEE_DETAILS_ROOT,
  LOSS_PAYEE_DETAILS_SAVE_AND_BACK: `${LOSS_PAYEE_DETAILS_ROOT}/save-and-back`,
  LOSS_PAYEE_DETAILS_CHANGE: `${LOSS_PAYEE_DETAILS_ROOT}/change`,
  LOSS_PAYEE_DETAILS_CHECK_AND_CHANGE: `${LOSS_PAYEE_DETAILS_ROOT}/check-and-change`,
  // TODO: remove ROOT from everything apart from the the root
  // TODO: add LOSS_PAYEE_FINANCIAL_UK = LOSS_PAYEE_FINANCIAL_DETAILS_UK
  // TODO: add LOSS_PAYEE_FINANCIAL_INTERNATIONAL_ = LOSS_PAYEE_FINANCIAL_DETAILS_INTERNATIONAL
  LOSS_PAYEE_FINANCIAL_UK_ROOT,
  LOSS_PAYEE_FINANCIAL_UK_ROOT_SAVE_AND_BACK: `${LOSS_PAYEE_FINANCIAL_UK_ROOT}/save-and-back`,
  LOSS_PAYEE_FINANCIAL_UK_ROOT_CHANGE: `${LOSS_PAYEE_FINANCIAL_UK_ROOT}/change`,
  LOSS_PAYEE_FINANCIAL_UK_ROOT_CHECK_AND_CHANGE: `${LOSS_PAYEE_FINANCIAL_UK_ROOT}/check-and-change`,
  LOSS_PAYEE_FINANCIAL_INTERNATIONAL_ROOT,
  LOSS_PAYEE_FINANCIAL_INTERNATIONAL_ROOT_SAVE_AND_BACK: `${LOSS_PAYEE_FINANCIAL_INTERNATIONAL_ROOT}/save-and-back`,
  LOSS_PAYEE_FINANCIAL_INTERNATIONAL_ROOT_CHANGE: `${LOSS_PAYEE_FINANCIAL_INTERNATIONAL_ROOT}/change`,
  LOSS_PAYEE_FINANCIAL_INTERNATIONAL_ROOT_CHECK_AND_CHANGE: `${LOSS_PAYEE_FINANCIAL_INTERNATIONAL_ROOT}/check-and-change`,
};

export default LOSS_PAYEE_ROUTES;
