import POLICY_ROOT from './root';

const PRE_CREDIT_PERIOD_ROOT = `${POLICY_ROOT}/pre-credit-period`;

const PRE_CREDIT_PERIOD_ROUTES = {
  PRE_CREDIT_PERIOD: PRE_CREDIT_PERIOD_ROOT,
  PRE_CREDIT_PERIOD_SAVE_AND_BACK: `${PRE_CREDIT_PERIOD_ROOT}/save-and-go-back`,
  PRE_CREDIT_PERIOD_CHANGE: `${PRE_CREDIT_PERIOD_ROOT}/change`,
  PRE_CREDIT_PERIOD_CHECK_AND_CHANGE: `${PRE_CREDIT_PERIOD_ROOT}/check-and-change`,
};

export default PRE_CREDIT_PERIOD_ROUTES;
