import POLICY_ROOT from './root';

const ROOT = `${POLICY_ROOT}/single-contract-policy`;

const SINGLE_CONTRACT_POLICY_ROUTES = {
  SINGLE_CONTRACT_POLICY: ROOT,
  SINGLE_CONTRACT_POLICY_SAVE_AND_BACK: `${ROOT}/save-and-go-back`,
  SINGLE_CONTRACT_POLICY_CHANGE: `${ROOT}/change`,
  SINGLE_CONTRACT_POLICY_CHECK_AND_CHANGE: `${ROOT}/check-and-change`,
  SINGLE_CONTRACT_POLICY_TOTAL_CONTRACT_VALUE: `${ROOT}/total-contract-value`,
  SINGLE_CONTRACT_POLICY_TOTAL_CONTRACT_VALUE_SAVE_AND_BACK: `${ROOT}/total-contract-value/save-and-go-back`,
  SINGLE_CONTRACT_POLICY_TOTAL_CONTRACT_VALUE_CHANGE: `${ROOT}/total-contract-value/change`,
  SINGLE_CONTRACT_POLICY_TOTAL_CONTRACT_VALUE_CHECK_AND_CHANGE: `${ROOT}/total-contract-value/check-and-change`,
};

export default SINGLE_CONTRACT_POLICY_ROUTES;
