const SECTION_KEYS = {
  APPLICATION_INFORMATION: 'APPLICATION_INFORMATION',
  ELIGIBILITY: 'ELIGIBILITY',
  EXPORTER_BUSINESS: 'EXPORTER_BUSINESS',
  POLICY: 'POLICY',
  BUYER: 'BUYER',
  EXPORT_CONTRACT: 'EXPORT_CONTRACT',
  DECLARATIONS: 'DECLARATIONS',
};

export default SECTION_KEYS;
