version: "3"
services:
  ui:
    build: ./ui
    image: exip/ui
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./ui/server:/app/server:ro
      - ./ui/public:/app/public:ro
      - ./ui/templates:/app/templates:ro
    command: npx nodemon server/index.js -L
