const FIELD_IDS = require('../constants/field-ids');
const FIELD_VALUES = require('../constants/field-values');

const {
  VALID_COMPANY_BASE,
  VALID_BUYER_BASE,
  TRIED_PRIVATE_COVER,
  FINAL_DESTINATION,
  UK_CONTENT_PERCENTAGE,
  CREDIT_LIMIT,
  PRE_CREDIT_PERIOD,
  CREDIT_PERIOD,
  POLICY_LENGTH,
  POLICY_TYPE,
} = FIELD_IDS;

const mockAnswers = {
  [VALID_COMPANY_BASE]: true,
  [VALID_BUYER_BASE]: true,
  [TRIED_PRIVATE_COVER]: true,
  [FINAL_DESTINATION]: 'France',
  [UK_CONTENT_PERCENTAGE]: 30,
  [CREDIT_LIMIT]: 123456,
  [PRE_CREDIT_PERIOD]: 12,
  [CREDIT_PERIOD]: 24,
  [POLICY_LENGTH]: 36,
  [POLICY_TYPE]: FIELD_VALUES.POLICY_TYPE.SINGLE,
};

module.exports = mockAnswers;
