name: "Retry Steps"
inputs:
  command:
    required: true
  working-directory:
    required: false
    default: "."
runs:
  using: "composite"
  steps:
    - run: |
        max_attempts=3
        attempt_num=1
        until [ $attempt_num -gt $max_attempts ]
        do
          echo "Attempt $attempt_num to run command"
          cd ${{ inputs.working-directory }} && ${{ inputs.command }} && break
          attempt_num=$((attempt_num + 1))
        done
        if [ $attempt_num -gt $max_attempts ]; then
          exit 1
        fi
      shell: bash