import type { GraphQLSchema } from 'graphql';
import { mergeSchemas } from '@graphql-tools/schema';
import typeDefs from './type-defs';
import customResolvers from '../custom-resolvers';

/**
 * KeystoneJS custom schema configuration
 * This extends the GraphQL schema automatically generated by KeystoneJS.
 * This allows us to add custom GraphQL resolvers.
 * @param GraphQLSchema - GraphQL schema definition
 * @returns GraphQLSchema - GraphQL schema definition
 */
export const extendGraphqlSchema = (schema: GraphQLSchema) =>
  mergeSchemas({
    schemas: [schema],
    typeDefs,
    resolvers: customResolvers,
  });
