import Context from '@keystone-6/core/types';
/**
 * disabled as importing from .keystone types causes linting error
 * lint does not realise that these are autogenerated by keystone
 */
/* eslint-disable */
import {
  ApplicationCreateInput,
  BuyerCreateInput,
  PolicyCreateInput,
  LossPayeeFinancialInternationalVectorCreateInput,
  LossPayeeFinancialUkVectorCreateInput,
} from '.keystone/types';
/* eslint-enable */
import { Account } from '../account';

export interface TestHelperCreate {
  context: Context;
  companyId?: string;
}

export interface TestHelperAccountCreate extends TestHelperCreate {
  data?: Account;
  deleteAccounts?: boolean;
}

export interface TestHelperAccountStatusCreate extends TestHelperCreate {
  data?: Account;
  deleteAccountStatus?: boolean;
  accountId: string;
}

export interface TestHelperApplicationCreate extends TestHelperCreate {
  data?: ApplicationCreateInput;
}

export interface TestHelperApplicationGet {
  context: Context;
  applicationId: string;
}

export interface TestHelperApplicationUpdate {
  context: Context;
  applicationId: string;
  data: object;
}

export interface TestHelperBuyerCreate extends TestHelperCreate {
  data: BuyerCreateInput;
}

export interface TestHelperPolicyCreate extends TestHelperCreate {
  data: PolicyCreateInput;
}

export interface TestHelperPolicyUpdate extends TestHelperCreate {
  data: PolicyCreateInput;
  policyId: string;
}

export interface TestHelperLossPayeeFinancialInternationalVectorCreate extends TestHelperCreate {
  data?: LossPayeeFinancialInternationalVectorCreateInput;
}

export interface TestHelperLossPayeeFinancialUkVectorCreate extends TestHelperCreate {
  data?: LossPayeeFinancialUkVectorCreateInput;
}
