export const ACCOUNT = {
  FIRST_NAME: 'firstName',
  LAST_NAME: 'lastName',
  EMAIL: 'email',
  PASSWORD: 'password',
  ACCESS_CODE: 'securityCode',
  VERIFICATION_EXPIRY: 'verificationExpiry',
  VERIFICATION_HASH: 'verificationHash',
  IS_VERIFIED: 'isVerified',
  IS_BLOCKED: 'isBlocked',
  PASSWORD_RESET_HASH: 'passwordResetHash',
  PASSWORD_RESET_EXPIRY: 'passwordResetExpiry',
  REACTIVATION_HASH: 'reactivationHash',
  REACTIVATION_EXPIRY: 'reactivationExpiry',
};
