import { EXTERNAL_API_DEFINITIONS } from '../../constants';
import { autoCompleteField } from '../../pages/shared';

const {
  CIS: { INVALID_COUNTRIES },
} = EXTERNAL_API_DEFINITIONS;

export const checkAutocompleteInput = {
  isVisible: (field) => {
    field.input().should('be.visible');
  },
  isNotVisible: (field) => {
    field.input().should('not.be.visible');
  },
  hasWorkingClientSideJS: (field) => {
    cy.checkClassName(field.input(), 'autocomplete__input autocomplete__input--default');
  },
  rendersInput: (field) => {
    field.input().should('exist');
  },
  rendersNoResultsMessage: (field, textValue) => {
    cy.keyboardInput(field.input(), textValue);

    const noResults = field.noResults();

    // this text is generated by external component.
    cy.checkText(noResults, 'No results found');
  },
  doesNotRenderFilteredCisCountries: (field) => {
    INVALID_COUNTRIES.forEach((invalidCountry) => {
      cy.keyboardInput(field.input(), invalidCountry);

      const noResults = field.noResults();
      noResults.should('exist');

      // this text is generated by external component.
      cy.checkText(noResults, 'No results found');
    });
  },
  rendersSingleResult: (field, input) => {
    // start searching for a country
    cy.keyboardInput(field.input(), input);

    const noResults = field.noResults();
    noResults.should('not.exist');

    const results = field.results();

    cy.assertLength(results, 1);
  },
  rendersMultipleResults: (field) => {
    cy.keyboardInput(field.input(), 'A');

    const noResults = field.noResults();
    noResults.should('not.exist');

    const results = field.results();

    results.should('have.length.greaterThan', 1);
  },
  allowsUserToRemoveCountryAndSearchAgain: (fieldId, country1, country2, expectedValue) => {
    cy.autocompleteKeyboardInput(fieldId, country1);
    // enter the second country
    cy.autocompleteKeyboardInput(fieldId, country2);

    cy.checkText(autoCompleteField(fieldId).results(), expectedValue);
  },
  checkInputResults: (fieldId, expectedValue) => {
    cy.checkText(autoCompleteField(fieldId).results(), expectedValue);
  },
  checkEmptyResults: (fieldId) => {
    autoCompleteField(fieldId).results().should('not.exist');
  },
};

export default checkAutocompleteInput;
