export const YOUR_BUYER = {
  COMPANY_OR_ORGANISATION: {
    NAME: 'companyOrOrganisationName',
    ADDRESS: 'address',
    COUNTRY: 'country',
    REGISTRATION_NUMBER: 'registrationNumber',
    WEBSITE: 'website',
    FIRST_NAME: 'contactFirstName',
    LAST_NAME: 'contactLastName',
    POSITION: 'contactPosition',
    EMAIL: 'contactEmail',
    CAN_CONTACT_BUYER: 'canContactBuyer',
  },
  CONNECTION_WITH_BUYER: 'exporterIsConnectedWithBuyer',
  CONNECTION_WITH_BUYER_DESCRIPTION: 'connectionWithBuyerDescription',
  TRADED_WITH_BUYER: 'exporterHasTradedWithBuyer',
  OUTSTANDING_PAYMENTS: 'outstandingPayments',
  TOTAL_OUTSTANDING_PAYMENTS: 'totalOutstandingPayments',
  TOTAL_OVERDUE_PAYMENTS: 'totalOverduePayments',
  PROVIDE_ALTERNATE_CURRENCY: 'provide-alternative-currency',
  FAILED_PAYMENTS: 'failedPayments',
  HAS_PREVIOUS_CREDIT_INSURANCE_COVER_WITH_BUYER: 'exporterHasPreviousCreditInsuranceWithBuyer',
  PREVIOUS_CREDIT_INSURANCE_COVER_WITH_BUYER: 'previousCreditInsuranceWithBuyerDescription',
};
