import POLICY_ROOT from './root';

const ROOT = `${POLICY_ROOT}/another-company`;

const OTHER_COMPANY_DETAILS_ROOT = `${ROOT}/other-company-details`;

const ANOTHER_COMPANY_ROUTES = {
  ANOTHER_COMPANY: ROOT,
  ANOTHER_COMPANY_SAVE_AND_BACK: `${ROOT}/save-and-go-back`,
  ANOTHER_COMPANY_CHANGE: `${ROOT}/change`,
  ANOTHER_COMPANY_CHECK_AND_CHANGE: `${ROOT}/check-and-change`,
  OTHER_COMPANY_DETAILS: OTHER_COMPANY_DETAILS_ROOT,
  OTHER_COMPANY_DETAILS_SAVE_AND_BACK: `${OTHER_COMPANY_DETAILS_ROOT}/save-and-go-back`,
  OTHER_COMPANY_DETAILS_CHANGE: `${OTHER_COMPANY_DETAILS_ROOT}/change`,
  OTHER_COMPANY_DETAILS_CHECK_AND_CHANGE: `${OTHER_COMPANY_DETAILS_ROOT}/check-and-change`,
};

export default ANOTHER_COMPANY_ROUTES;
