const ROOT = '/export-contract';
const ABOUT_GOODS_OR_SERVICES_ROOT = `${ROOT}/about-goods-or-services`;
const HOW_WILL_YOU_GET_PAID_ROOT = `${ROOT}/how-will-you-get-paid`;
const PRIVATE_MARKET_ROOT = `${ROOT}/private-market`;
const DECLINED_BY_PRIVATE_MARKET_ROOT = `${ROOT}/declined-by-private-market`;
const AGENT_ROOT = `${ROOT}/agent`;

export const EXPORT_CONTRACT = {
  ROOT,
  ABOUT_GOODS_OR_SERVICES: ABOUT_GOODS_OR_SERVICES_ROOT,
  ABOUT_GOODS_OR_SERVICES_SAVE_AND_BACK: `${ABOUT_GOODS_OR_SERVICES_ROOT}/save-and-go-back`,
  ABOUT_GOODS_OR_SERVICES_CHANGE: `${ABOUT_GOODS_OR_SERVICES_ROOT}/change`,
  ABOUT_GOODS_OR_SERVICES_CHECK_AND_CHANGE: `${ABOUT_GOODS_OR_SERVICES_ROOT}/check-and-change`,
  HOW_WILL_YOU_GET_PAID: HOW_WILL_YOU_GET_PAID_ROOT,
  HOW_WILL_YOU_GET_PAID_SAVE_AND_BACK: `${HOW_WILL_YOU_GET_PAID_ROOT}/save-and-go-back`,
  HOW_WILL_YOU_GET_PAID_CHANGE: `${HOW_WILL_YOU_GET_PAID_ROOT}/change`,
  HOW_WILL_YOU_GET_PAID_CHECK_AND_CHANGE: `${HOW_WILL_YOU_GET_PAID_ROOT}/check-and-change`,
  PRIVATE_MARKET: PRIVATE_MARKET_ROOT,
  PRIVATE_MARKET_SAVE_AND_BACK: `${PRIVATE_MARKET_ROOT}/save-and-go-back`,
  PRIVATE_MARKET_CHANGE: `${PRIVATE_MARKET_ROOT}/change`,
  PRIVATE_MARKET_CHECK_AND_CHANGE: `${PRIVATE_MARKET_ROOT}/check-and-change`,
  DECLINED_BY_PRIVATE_MARKET: DECLINED_BY_PRIVATE_MARKET_ROOT,
  AGENT: AGENT_ROOT,
  CHECK_YOUR_ANSWERS: `${ROOT}/check-your-answers`,
};
