const ROOT = '/policy';
const BROKER_ROOT = `${ROOT}/broker`;

export const POLICY = {
  ROOT,
  TYPE_OF_POLICY: `${ROOT}/type-of-policy`,
  TYPE_OF_POLICY_SAVE_AND_BACK: `${ROOT}/type-of-policy/save-and-go-back`,
  TYPE_OF_POLICY_CHANGE: `${ROOT}/type-of-policy/change`,
  TYPE_OF_POLICY_CHECK_AND_CHANGE: `${ROOT}/type-of-policy/check-and-change`,
  SINGLE_CONTRACT_POLICY: `${ROOT}/single-contract-policy`,
  SINGLE_CONTRACT_POLICY_SAVE_AND_BACK: `${ROOT}/single-contract-policy/save-and-go-back`,
  SINGLE_CONTRACT_POLICY_CHANGE: `${ROOT}/single-contract-policy/change`,
  SINGLE_CONTRACT_POLICY_CHECK_AND_CHANGE: `${ROOT}/single-contract-policy/check-and-change`,
  MULTIPLE_CONTRACT_POLICY: `${ROOT}/multi-contract-policy`,
  MULTIPLE_CONTRACT_POLICY_SAVE_AND_BACK: `${ROOT}/multi-contract-policy/save-and-go-back`,
  MULTIPLE_CONTRACT_POLICY_CHANGE: `${ROOT}/multi-contract-policy/change`,
  MULTIPLE_CONTRACT_POLICY_CHECK_AND_CHANGE: `${ROOT}/multi-contract-policy/check-and-change`,
  ABOUT_GOODS_OR_SERVICES: `${ROOT}/about-goods-or-services`,
  ABOUT_GOODS_OR_SERVICES_SAVE_AND_BACK: `${ROOT}/about-goods-or-services/save-and-go-back`,
  ABOUT_GOODS_OR_SERVICES_CHANGE: `${ROOT}/about-goods-or-services/change`,
  ABOUT_GOODS_OR_SERVICES_CHECK_AND_CHANGE: `${ROOT}/about-goods-or-services/check-and-change`,
  NAME_ON_POLICY: `${ROOT}/name-on-policy`,
  NAME_ON_POLICY_SAVE_AND_BACK: `${ROOT}/name-on-policy/save-and-go-back`,
  NAME_ON_POLICY_CHANGE: `${ROOT}/name-on-policy/change`,
  NAME_ON_POLICY_CHECK_AND_CHANGE: `${ROOT}/name-on-policy/check-and-change`,
  DIFFERENT_NAME_ON_POLICY: `${ROOT}/different-name-on-policy`,
  DIFFERENT_NAME_ON_POLICY_SAVE_AND_BACK: `${ROOT}/different-name-on-policy/save-and-go-back`,
  DIFFERENT_NAME_ON_POLICY_CHANGE: `${ROOT}/different-name-on-policy/change`,
  DIFFERENT_NAME_ON_POLICY_CHECK_AND_CHANGE: `${ROOT}/different-name-on-policy/check-and-change`,
  BROKER_ROOT,
  BROKER_SAVE_AND_BACK: `${BROKER_ROOT}/save-and-back`,
  BROKER_CHANGE: `${BROKER_ROOT}/change`,
  BROKER_CHECK_AND_CHANGE: `${BROKER_ROOT}/check-and-change`,
  CHECK_YOUR_ANSWERS: `${ROOT}/check-your-answers`,
  CHECK_YOUR_ANSWERS_SAVE_AND_BACK: `${ROOT}/check-your-answers/save-and-go-back`,
};
