const ROOT = '/policy';
const BROKER_ROOT = `${ROOT}/broker`;
const BROKER_DETAILS_ROOT = `${ROOT}/broker-details`;
const BROKER_CONFIRM_ADDRESS_ROOT = `${ROOT}/broker-confirm-address`;
const NAME_ON_POLICY_ROOT = `${ROOT}/contact`;
const DIFFERENT_NAME_ON_POLICY_ROOT = `${ROOT}/contact-details`;
const LOSS_PAYEE_ROOT = `${ROOT}/loss-payee`;
const LOSS_PAYEE_DETAILS_ROOT = `${ROOT}/loss-payee-details`;
const LOSS_PAYEE_FINANCIAL_UK_ROOT = `${ROOT}/loss-payee-bank-details`;
const LOSS_PAYEE_FINANCIAL_INTERNATIONAL_ROOT = `${ROOT}/loss-payee-international-bank-details`;

export const POLICY = {
  ROOT,
  TYPE_OF_POLICY: `${ROOT}/type-of-policy`,
  TYPE_OF_POLICY_SAVE_AND_BACK: `${ROOT}/type-of-policy/save-and-go-back`,
  TYPE_OF_POLICY_CHANGE: `${ROOT}/type-of-policy/change`,
  TYPE_OF_POLICY_CHECK_AND_CHANGE: `${ROOT}/type-of-policy/check-and-change`,
  SINGLE_CONTRACT_POLICY: `${ROOT}/single-contract-policy`,
  SINGLE_CONTRACT_POLICY_SAVE_AND_BACK: `${ROOT}/single-contract-policy/save-and-go-back`,
  SINGLE_CONTRACT_POLICY_CHANGE: `${ROOT}/single-contract-policy/change`,
  SINGLE_CONTRACT_POLICY_CHECK_AND_CHANGE: `${ROOT}/single-contract-policy/check-and-change`,
  SINGLE_CONTRACT_POLICY_TOTAL_CONTRACT_VALUE: `${ROOT}/single-contract-policy/total-contract-value`,
  SINGLE_CONTRACT_POLICY_TOTAL_CONTRACT_VALUE_SAVE_AND_BACK: `${ROOT}/single-contract-policy/total-contract-value/save-and-go-back`,
  SINGLE_CONTRACT_POLICY_TOTAL_CONTRACT_VALUE_CHANGE: `${ROOT}/single-contract-policy/total-contract-value/change`,
  SINGLE_CONTRACT_POLICY_TOTAL_CONTRACT_VALUE_CHECK_AND_CHANGE: `${ROOT}/single-contract-policy/total-contract-value/check-and-change`,
  MULTIPLE_CONTRACT_POLICY: `${ROOT}/multiple-contract-policy`,
  MULTIPLE_CONTRACT_POLICY_SAVE_AND_BACK: `${ROOT}/multiple-contract-policy/save-and-go-back`,
  MULTIPLE_CONTRACT_POLICY_CHANGE: `${ROOT}/multiple-contract-policy/change`,
  MULTIPLE_CONTRACT_POLICY_CHECK_AND_CHANGE: `${ROOT}/multiple-contract-policy/check-and-change`,
  MULTIPLE_CONTRACT_POLICY_EXPORT_VALUE: `${ROOT}/multiple-contract-policy/export-value`,
  MULTIPLE_CONTRACT_POLICY_EXPORT_VALUE_SAVE_AND_BACK: `${ROOT}/multiple-contract-policy/export-value/save-and-go-back`,
  MULTIPLE_CONTRACT_POLICY_EXPORT_VALUE_CHANGE: `${ROOT}/multiple-contract-policy/export-value/change`,
  MULTIPLE_CONTRACT_POLICY_EXPORT_VALUE_CHECK_AND_CHANGE: `${ROOT}/multiple-contract-policy/export-value/check-and-change`,
  NAME_ON_POLICY: NAME_ON_POLICY_ROOT,
  NAME_ON_POLICY_SAVE_AND_BACK: `${NAME_ON_POLICY_ROOT}/save-and-go-back`,
  NAME_ON_POLICY_CHANGE: `${NAME_ON_POLICY_ROOT}/change`,
  NAME_ON_POLICY_CHECK_AND_CHANGE: `${NAME_ON_POLICY_ROOT}/check-and-change`,
  DIFFERENT_NAME_ON_POLICY: `${DIFFERENT_NAME_ON_POLICY_ROOT}`,
  DIFFERENT_NAME_ON_POLICY_SAVE_AND_BACK: `${DIFFERENT_NAME_ON_POLICY_ROOT}/save-and-go-back`,
  DIFFERENT_NAME_ON_POLICY_CHANGE: `${DIFFERENT_NAME_ON_POLICY_ROOT}/change`,
  DIFFERENT_NAME_ON_POLICY_CHECK_AND_CHANGE: `${DIFFERENT_NAME_ON_POLICY_ROOT}/check-and-change`,
  PRE_CREDIT_PERIOD: `${ROOT}/pre-credit-period`,
  PRE_CREDIT_PERIOD_SAVE_AND_BACK: `${ROOT}/pre-credit-period/save-and-go-back`,
  PRE_CREDIT_PERIOD_CHANGE: `${ROOT}/pre-credit-period/change`,
  PRE_CREDIT_PERIOD_CHECK_AND_CHANGE: `${ROOT}/pre-credit-period/check-and-change`,
  ANOTHER_COMPANY: `${ROOT}/another-company`,
  ANOTHER_COMPANY_SAVE_AND_BACK: `${ROOT}/another-company/save-and-go-back`,
  OTHER_COMPANY_DETAILS: `${ROOT}/other-company-details`,
  OTHER_COMPANY_DETAILS_SAVE_AND_BACK: `${ROOT}/other-company-details/save-and-go-back`,
  BROKER_ROOT,
  BROKER_SAVE_AND_BACK: `${BROKER_ROOT}/save-and-back`,
  BROKER_CHANGE: `${BROKER_ROOT}/change`,
  BROKER_CHECK_AND_CHANGE: `${BROKER_ROOT}/check-and-change`,
  BROKER_DETAILS_ROOT,
  BROKER_DETAILS_SAVE_AND_BACK: `${BROKER_DETAILS_ROOT}/save-and-back`,
  BROKER_DETAILS_CHANGE: `${BROKER_DETAILS_ROOT}/change`,
  BROKER_DETAILS_CHECK_AND_CHANGE: `${BROKER_DETAILS_ROOT}/check-and-change`,
  BROKER_CONFIRM_ADDRESS_ROOT,
  LOSS_PAYEE_ROOT,
  LOSS_PAYEE_SAVE_AND_BACK: `${LOSS_PAYEE_ROOT}/save-and-back`,
  LOSS_PAYEE_CHANGE: `${LOSS_PAYEE_ROOT}/change`,
  LOSS_PAYEE_CHECK_AND_CHANGE: `${LOSS_PAYEE_ROOT}/check-and-change`,
  LOSS_PAYEE_DETAILS_ROOT,
  LOSS_PAYEE_DETAILS_CHANGE: `${LOSS_PAYEE_DETAILS_ROOT}/change`,
  LOSS_PAYEE_DETAILS_CHECK_AND_CHANGE: `${LOSS_PAYEE_DETAILS_ROOT}/check-and-change`,
  LOSS_PAYEE_FINANCIAL_UK_ROOT,
  LOSS_PAYEE_FINANCIAL_UK_ROOT_SAVE_AND_BACK: `${LOSS_PAYEE_FINANCIAL_UK_ROOT}/save-and-back`,
  LOSS_PAYEE_FINANCIAL_UK_ROOT_CHANGE: `${LOSS_PAYEE_FINANCIAL_UK_ROOT}/change`,
  LOSS_PAYEE_FINANCIAL_UK_ROOT_CHECK_AND_CHANGE: `${LOSS_PAYEE_FINANCIAL_UK_ROOT}/check-and-change`,
  // TODO: remove ROOT from everything apart from the the root
  LOSS_PAYEE_FINANCIAL_INTERNATIONAL_ROOT,
  LOSS_PAYEE_FINANCIAL_INTERNATIONAL_ROOT_SAVE_AND_BACK: `${LOSS_PAYEE_FINANCIAL_UK_ROOT}/save-and-back`,
  LOSS_PAYEE_FINANCIAL_INTERNATIONAL_ROOT_CHANGE: `${LOSS_PAYEE_FINANCIAL_UK_ROOT}/change`,
  LOSS_PAYEE_FINANCIAL_INTERNATIONAL_ROOT_CHECK_AND_CHANGE: `${LOSS_PAYEE_FINANCIAL_UK_ROOT}/check-and-change`,
  CHECK_YOUR_ANSWERS: `${ROOT}/check-your-answers`,
};
