const ROOT = '/your-buyer';
const COMPANY_OR_ORGANISATION_ROOT = `${ROOT}/buyer-company-organisation`;
const WORKING_WITH_BUYER_ROOT = `${ROOT}/working-with-buyer`;
const CONNECTION_TO_THE_BUYER_ROOT = `${ROOT}/connection-to-the-buyer`;
const CHECK_YOUR_ANSWERS = `${ROOT}/check-your-answers`;

export const YOUR_BUYER = {
  ROOT,
  COMPANY_OR_ORGANISATION: COMPANY_OR_ORGANISATION_ROOT,
  COMPANY_OR_ORGANISATION_CHANGE: `${COMPANY_OR_ORGANISATION_ROOT}/change`,
  COMPANY_OR_ORGANISATION_CHECK_AND_CHANGE: `${COMPANY_OR_ORGANISATION_ROOT}/check-and-change`,
  COMPANY_OR_ORGANISATION_SAVE_AND_BACK: `${COMPANY_OR_ORGANISATION_ROOT}/save-and-back`,
  WORKING_WITH_BUYER: WORKING_WITH_BUYER_ROOT,
  WORKING_WITH_BUYER_CHANGE: `${WORKING_WITH_BUYER_ROOT}/change`,
  WORKING_WITH_BUYER_CHECK_AND_CHANGE: `${WORKING_WITH_BUYER_ROOT}/check-and-change`,
  WORKING_WITH_BUYER_SAVE_AND_BACK: `${WORKING_WITH_BUYER_ROOT}/save-and-back`,
  CONNECTION_TO_THE_BUYER: CONNECTION_TO_THE_BUYER_ROOT,
  CONNECTION_TO_THE_BUYER_SAVE_AND_BACK: `${CONNECTION_TO_THE_BUYER_ROOT}/save-and-back`,
  CHECK_YOUR_ANSWERS,
  CHECK_YOUR_ANSWERS_SAVE_AND_BACK: `${CHECK_YOUR_ANSWERS}/save-and-back`,
};
