const ROOT = '/your-buyer';
const COMPANY_OR_ORGANISATION_ROOT = `${ROOT}/buyer-company-organisation`;
const TRADED_WITH_BUYER_ROOT = `${ROOT}/prior-trade-history`;
const CONNECTION_WITH_BUYER_ROOT = `${ROOT}/connection-with-the-buyer`;
const TRADING_HISTORY_ROOT = `${ROOT}/trading-history`;
const ALTERNATIVE_CURRENCY_ROOT = `${ROOT}/alternative-currency`;
const CREDIT_INSURANCE_COVER_ROOT = `${ROOT}/credit-insurance-cover`;
const BUYER_FINANCIAL_INFORMATION_ROOT = `${ROOT}/buyer-financial-information`;
const CHECK_YOUR_ANSWERS = `${ROOT}/check-your-answers`;

export const YOUR_BUYER = {
  ROOT,
  COMPANY_OR_ORGANISATION: COMPANY_OR_ORGANISATION_ROOT,
  COMPANY_OR_ORGANISATION_CHANGE: `${COMPANY_OR_ORGANISATION_ROOT}/change`,
  COMPANY_OR_ORGANISATION_CHECK_AND_CHANGE: `${COMPANY_OR_ORGANISATION_ROOT}/check-and-change`,
  COMPANY_OR_ORGANISATION_SAVE_AND_BACK: `${COMPANY_OR_ORGANISATION_ROOT}/save-and-back`,
  TRADED_WITH_BUYER: TRADED_WITH_BUYER_ROOT,
  TRADED_WITH_BUYER_CHANGE: `${TRADED_WITH_BUYER_ROOT}/change`,
  TRADED_WITH_BUYER_CHECK_AND_CHANGE: `${TRADED_WITH_BUYER_ROOT}/check-and-change`,
  TRADED_WITH_BUYER_SAVE_AND_BACK: `${TRADED_WITH_BUYER_ROOT}/save-and-back`,
  CONNECTION_WITH_BUYER: CONNECTION_WITH_BUYER_ROOT,
  CONNECTION_WITH_BUYER_SAVE_AND_BACK: `${CONNECTION_WITH_BUYER_ROOT}/save-and-back`,
  CONNECTION_WITH_BUYER_CHANGE: `${CONNECTION_WITH_BUYER_ROOT}/change`,
  CONNECTION_WITH_BUYER_CHECK_AND_CHANGE: `${CONNECTION_WITH_BUYER_ROOT}/check-and-change`,
  TRADING_HISTORY: TRADING_HISTORY_ROOT,
  TRADING_HISTORY_SAVE_AND_BACK: `${TRADING_HISTORY_ROOT}/save-and-back`,
  TRADING_HISTORY_CHANGE: `${TRADING_HISTORY_ROOT}/change`,
  TRADING_HISTORY_CHECK_AND_CHANGE: `${TRADING_HISTORY_ROOT}/check-and-change`,
  ALTERNATIVE_CURRENCY: ALTERNATIVE_CURRENCY_ROOT,
  CREDIT_INSURANCE_COVER: CREDIT_INSURANCE_COVER_ROOT,
  CREDIT_INSURANCE_COVER_SAVE_AND_BACK: `${CREDIT_INSURANCE_COVER_ROOT}/save-and-back`,
  CREDIT_INSURANCE_COVER_CHANGE: `${CREDIT_INSURANCE_COVER_ROOT}/change`,
  CREDIT_INSURANCE_COVER_CHECK_AND_CHANGE: `${CREDIT_INSURANCE_COVER_ROOT}/check-and-change`,
  BUYER_FINANCIAL_INFORMATION: BUYER_FINANCIAL_INFORMATION_ROOT,
  BUYER_FINANCIAL_INFORMATION_SAVE_AND_BACK: `${BUYER_FINANCIAL_INFORMATION_ROOT}/save-and-back`,
  BUYER_FINANCIAL_INFORMATION_CHANGE: `${BUYER_FINANCIAL_INFORMATION_ROOT}/change`,
  BUYER_FINANCIAL_INFORMATION_CHECK_AND_CHANGE: `${BUYER_FINANCIAL_INFORMATION_ROOT}/check-and-change`,
  CHECK_YOUR_ANSWERS,
};
