const FIELD_IDS = require('./field-ids');
const ROUTES = require('./routes');
const { FIELDS } = require('../content-strings');

const FIELD_GROUPS = {
  COMPANY_DETAILS: {
    FIELDS: [
      {
        ID: FIELD_IDS.VALID_COMPANY_BASE,
        ...FIELDS[FIELD_IDS.VALID_COMPANY_BASE],
        CHANGE_ROUTE: ROUTES.COMPANY_BASED_CHANGE,
      },
    ],
  },
  EXPORT_DETAILS: {
    FIELDS: [
      {
        ID: FIELD_IDS.VALID_BUYER_BASE,
        ...FIELDS[FIELD_IDS.VALID_BUYER_BASE],
        CHANGE_ROUTE: ROUTES.BUYER_BASED_CHANGE,
      },
      {
        ID: FIELD_IDS.TRIED_PRIVATE_COVER,
        ...FIELDS[FIELD_IDS.TRIED_PRIVATE_COVER],
        CHANGE_ROUTE: ROUTES.TRIED_TO_OBTAIN_COVER_CHANGE,
      },
      {
        ID: FIELD_IDS.FINAL_DESTINATION,
        ...FIELDS[FIELD_IDS.FINAL_DESTINATION],
        CHANGE_ROUTE: ROUTES.FINAL_DESTINATION_CHANGE,
      },
      {
        ID: FIELD_IDS.UK_CONTENT_PERCENTAGE,
        ...FIELDS[FIELD_IDS.UK_CONTENT_PERCENTAGE],
        CHANGE_ROUTE: ROUTES.UK_CONTENT_PERCENTAGE_CHANGE,
      },
    ],
  },
  DEAL_DETAILS: {
    FIELDS: [
      {
        ID: FIELD_IDS.CURRENCY,
        ...FIELDS[FIELD_IDS.CURRENCY],
        CHANGE_ROUTE: ROUTES.TELL_US_ABOUT_YOUR_DEAL_CHANGE,
      },
      {
        ID: FIELD_IDS.AMOUNT,
        ...FIELDS[FIELD_IDS.AMOUNT],
        CHANGE_ROUTE: ROUTES.TELL_US_ABOUT_YOUR_DEAL_CHANGE,
      },
      {
        ID: FIELD_IDS.CREDIT_PERIOD,
        ...FIELDS[FIELD_IDS.CREDIT_PERIOD],
        CHANGE_ROUTE: ROUTES.TELL_US_ABOUT_YOUR_DEAL_CHANGE,
      },
      {
        ID: FIELD_IDS.SINGLE_POLICY_LENGTH,
        ...FIELDS[FIELD_IDS.SINGLE_POLICY_LENGTH],
        CHANGE_ROUTE: ROUTES.TELL_US_ABOUT_YOUR_DEAL_CHANGE,
      },
      {
        ID: FIELD_IDS.MULTI_POLICY_LENGTH,
        ...FIELDS[FIELD_IDS.MULTI_POLICY_LENGTH],
        CHANGE_ROUTE: ROUTES.TELL_US_ABOUT_YOUR_DEAL_CHANGE,
      },
      {
        ID: FIELD_IDS.POLICY_TYPE,
        ...FIELDS[FIELD_IDS.POLICY_TYPE],
        CHANGE_ROUTE: ROUTES.TELL_US_ABOUT_YOUR_DEAL_CHANGE,
      },
    ],
  },
};

module.exports = FIELD_GROUPS;
