export const MINIMUM_CHARACTERS = {
  SORT_CODE: 6,
  ACCOUNT_NUMBER: 6,
  BIC_SWIFT_CODE: 8,
  IBAN: 16,
};

export const MAXIMUM_CHARACTERS = {
  EMAIL: 300,
  FULL_ADDRESS: 500,
  SORT_CODE: 6,
  ACCOUNT_NUMBER: 8,
  BIC_SWIFT_CODE: 11,
  IBAN: 34,
  ABOUT_GOODS_OR_SERVICES_DESCRIPTION: 1000,
  CREDIT_PERIOD_WITH_BUYER: 1000,
  PREVIOUS_CREDIT_INSURANCE_COVER_WITH_BUYER: 1000,
  FEEDBACK: {
    IMPROVEMENT: 1200,
    OTHER_COMMENTS: 1200,
  },
  PAYMENT_TERMS_DESCRIPTION: 1000,
  DECLINED_BY_PRIVATE_MARKET_DESCRIPTION: 1000,
};
