export const MINIMUM_CHARACTERS = {
  ZERO: 0,
  ONE: 1,
  SORT_CODE: 6,
  ACCOUNT_NUMBER: 6,
  BIC_SWIFT_CODE: 8,
  BUSINESS: {
    EMPLOYEES_UK: 1,
  },
  BUYER: {
    TOTAL_OUSTANDING: 1,
  },
  IBAN: 16,
  POLICY: {
    COST: 1,
    MAXIMUM_BUYER_WILL_OWE: 1,
    REQUESTED_CREDIT_LIMIT: 1,
    TOTAL_CONTRACT_VALUE: 1,
    TOTAL_SALES_TO_BUYER: 1,
  },
  QUOTE: {
    CREDIT_PERIOD: 1,
    POLICY_LENGTH: 1,
  },
};

export const MAXIMUM_CHARACTERS = {
  ABOUT_GOODS_OR_SERVICES_DESCRIPTION: 1000,
  ACCOUNT_NUMBER: 8,
  ACCOUNT: {
    NAME: 400,
  },
  AGENT_NAME: 800,
  AGENT_SERVICE_DESCRIPTION: 1000,
  BIC_SWIFT_CODE: 11,
  BROKER_NAME: 800,
  BROKER_BUILDING_NUMBER_OR_NAME: 100,
  BUSINESS: {
    GOODS_OR_SERVICES_DESCRIPTION: 1000,
  },
  BUYER: {
    COMPANY_OR_ORGANISATION: 200,
    REGISTRATION_NUMBER: 200,
    PREVIOUS_CREDIT_INSURANCE_COVER: 1000,
  },
  COMPANY_DIFFERENT_TRADING_NAME: 200,
  CONNECTION_WITH_BUYER_DESCRIPTION: 1000,
  CREDIT_PERIOD_WITH_BUYER: 1000,
  DECLARATIONS: {
    MODERN_SLAVERY: {
      CONDITIONAL_REASON: 1000,
    },
  },
  DECLINED_BY_PRIVATE_MARKET_DESCRIPTION: 1000,
  DIFFERENT_NAME_ON_POLICY_POSITION: 50,
  DIFFERENT_NAME_ON_POLICY: 50,
  EMAIL: 300,
  EXPORT_CONTRACT: {
    OTHER_AWARD_METHOD: 200,
  },
  FEEDBACK: {
    IMPROVEMENT: 1200,
    OTHER_COMMENTS: 1200,
  },
  FULL_ADDRESS: 500,
  IBAN: 34,
  LOSS_PAYEE_NAME: 200,
  NAME_ON_POLICY_POSITION: 50,
  PAYMENT_TERMS_DESCRIPTION: 1000,
  PERCENTAGE: 100,
  POLICY_CONTACT_NAME: 400,
  QUOTE: {
    CREDIT_PERIOD: 2,
  },
  REQUESTED_JOINTLY_INSURED_PARTY: {
    COMPANY_NAME: 200,
    COMPANY_NUMBER: 100,
  },
  SORT_CODE: 6,
};
