import { APPLICATION } from '..';

const INITIAL_APPLICATION_DATA = {
  status: APPLICATION.STATUS.IN_PROGRESS,
  version: APPLICATION.LATEST_VERSION_NUMBER,
  dealType: APPLICATION.DEAL_TYPE,
  submissionCount: APPLICATION.SUBMISSION_COUNT_DEFAULT,
};

export default INITIAL_APPLICATION_DATA;
