import { APPLICATION } from '..';

const { STATUS, LATEST_VERSION_NUMBER, DEAL_TYPE, SUBMISSION_COUNT_DEFAULT } = APPLICATION;
const INITIAL_APPLICATION_DATA = {
  status: STATUS.IN_PROGRESS,
  version: LATEST_VERSION_NUMBER,
  dealType: DEAL_TYPE,
  submissionCount: SUBMISSION_COUNT_DEFAULT,
};

export default INITIAL_APPLICATION_DATA;
