export const BUTTONS = {
  BACK_TO_SERVICE: 'Back to service',
  CHANGE_ANSWERS_START_NEW_APPLICATION: 'Change answers and start a new application',
  CONTINUE: 'Continue',
  CONTINUE_NEXT_SECTION: 'Continue to next section',
  CONFIRM: 'Confirm',
  CONFIRM_AND_CONTINUE: 'Confirm and continue',
  CONTINUE_TO_SIGN_IN: 'Continue to sign in',
  GET_A_QUOTE_FOR_INSURANCE: 'Get a quote for credit insurance',
  NEXT: 'Next',
  PREVIOUS: 'Previous',
  REACTIVATE_ACCOUNT: 'Reactivate account',
  RETURN_TO_EXISTING_APPLICATION: 'Return to my existing application',
  RETURN_TO_SERVICE: 'Return to service',
  RETURN_TO_SIGN_IN: 'Return to sign in',
  SAVE_CHANGES: 'Save changes',
  SAVE_AND_BACK: 'Save and back to all sections',
  SEARCH: 'Search',
  SEND_NEW_SECURITY_CODE: 'Send new security code',
  SEND_NEW_LINK: 'Send me a new link',
  SEND_FEEDBACK: 'Send feedback',
  START_APPLICATION: 'Start an application',
  START_NEW_APPLICATION: 'Start new application',
  START_A_NEW_APPLICATION: 'Start a new application',
  START_DIFFERENT_SECTION: 'Start a different section',
  START_NOW: 'Start now',
  SUBMIT: 'Submit',
  SUBMIT_APPLICATION: 'Submit application',
  SIGN_IN: 'Sign in',
  USE_THIS_ADDRESS: 'Use this address',
};
