export const BUTTONS = {
  CONTINUE: 'Continue',
  CONTINUE_NEXT_SECTION: 'Continue to next section',
  CONFIRM_AND_CONTINUE: 'Confirm and continue',
  SUBMIT: 'Submit',
  START_APPLICATION: 'Start an application',
  START_NEW_APPLICATION: 'Start new application',
  START_A_NEW_APPLICATION: 'Start a new application',
  SUBMIT_APPLICATION: 'Submit application',
  START_NOW: 'Start now',
  SAVE_CHANGES: 'Save changes',
  SAVE_AND_BACK: 'Save and back to all sections',
  CHANGE_ANSWERS_START_NEW_APPLICATION: 'Change answers and start new application',
  SEARCH: 'Search',
  SIGN_IN: 'Sign in',
  SEND_NEW_SECURITY_CODE: 'Send new security code',
};
