import { UKEF_CONTACT_DETAILS } from '../constants';

export const CONTACT_DETAILS = {
  EMAIL: {
    PREFIX: 'Email',
    TEXT: UKEF_CONTACT_DETAILS.EMAIL.CREDIT_INSURANCE_SUPPORT,
    VALUE: `mailto:${UKEF_CONTACT_DETAILS.EMAIL.CREDIT_INSURANCE_SUPPORT}`,
  },
  UNDERWRITING_EMAIL: {
    PREFIX: 'Email',
    TEXT: UKEF_CONTACT_DETAILS.EMAIL.UNDERWRITING,
    VALUE: `mailto:${UKEF_CONTACT_DETAILS.EMAIL.UNDERWRITING}`,
  },
  PHONE: {
    PREFIX: 'Phone',
    VALUE: UKEF_CONTACT_DETAILS.PHONE,
  },
  OPENING_TIMES: 'Opening times: Monday to Friday, 9am to 5pm (excluding public holidays)',
};
