import * as dotenv from 'dotenv';

dotenv.config();

const { NODE_ENV } = process.env;

const isDevEnvironment = NODE_ENV === 'development';

/**
 * An array of allowed resolvers automatically generated by KeystoneJS.
 * All other automatically generated resolvers are not allowed to be executed.
 */
export const DEFAULT_RESOLVERS = [
  // application
  'updateBroker',
  'updateBusiness',
  'updateBuyer',
  'updateBuyerRelationship',
  'updateBuyerTradingHistory',
  'updateCompany',
  'updateDeclaration',
  'updateDeclarationModernSlavery',
  'updateNominatedLossPayee',
  'updateJointlyInsuredParty',
  'updatePolicy',
  'updatePolicyContact',
  'updateExportContract',
  'updateExportContractAgent',
  'updateExportContractAgentService',
  'updateExportContractAgentServiceCharge',
  'updatePrivateMarket',
  'updateSectionReview',
  'updateEligibility',
  'updateCompanyDifferentTradingAddress',
  'referenceNumber',
  'applications',

  // account
  'account',
  'updateAccount',

  // misc
  'countries',
];

/**
 * An array of allowed resolvers manually generated outside of KeystoneJS.
 * Any other manually generated resolvers are not allowed to be executed.
 */
export const CUSTOM_RESOLVERS = [
  // account
  'accountPasswordReset',
  'accountSignIn',
  'accountSignInSendNewCode',
  'createAnAccount',
  'sendEmailConfirmEmailAddress',
  'sendEmailPasswordResetLink',
  'sendEmailReactivateAccountLink',
  'updateLossPayeeFinancialDetailsUk',
  'updateLossPayeeFinancialDetailsInternational',
  'verifyAccountEmailAddress',
  'verifyAccountPasswordResetToken',
  'verifyAccountReactivationToken',
  'verifyAccountSignInCode',

  // application
  'createAnApplication',
  'declarationAntiBriberies',
  'declarationConfirmationAndAcknowledgements',
  'declarationHowDataWillBeUseds',
  'deleteApplicationByReferenceNumber',
  'getApplicationByReferenceNumber',
  'getCompaniesHouseInformation',
  'getOrdnanceSurveyAddresses',
  'submitApplication',

  // feedback
  'createFeedbackAndSendEmail',

  // countries and currencies
  'getApimCisCountries',
  'getApimCurrencies',
  'getCountriesAndCurrencies',
];

/**
 * An array of resolvers added for dev/testing purposes only.
 * These should not be available in non-dev environments.
 */
export const DEV_ENVIRONMENT_CUSTOM_RESOLVERS = [
  'accounts',
  'addAndGetOTP',
  'createApplications',
  'createAnAbandonedApplication',
  'createManyApplications',
  'createBuyer',
  'deleteAnAccount',
  'deleteApplications',
  'getAccountPasswordResetToken',
  'updateAccountStatus',
];

/**
 * If the environment is a dev environment,
 * Add dev environment specific resolvers
 */
if (isDevEnvironment) {
  CUSTOM_RESOLVERS.push(...DEV_ENVIRONMENT_CUSTOM_RESOLVERS);
}

/**
 * An array of allowed resolvers:
 * - Automatically generated by KeystoneJS
 * - Manually generated by KeystoneJS
 * Any other resolvers are not allowed to be executed.
 */
export const ALLOWED_GRAPHQL_RESOLVERS = [...DEFAULT_RESOLVERS, ...CUSTOM_RESOLVERS];

export default ALLOWED_GRAPHQL_RESOLVERS;
