/**
 * An array of allowed resolvers automatically generated by KeystoneJS.
 * All other automatically generated resolvers are not allowed to be executed.
 */
const DEFAULT_RESOLVERS = [
  // application
  'createApplication',
  'updateBroker',
  'updateBusinessContactDetail',
  'updateBusiness',
  'updateBuyer',
  'updateDeclaration',
  'updatePolicyAndExport',
  'updateSectionReview',
  'updateEligibility',
  'referenceNumber',
  'applications',

  // account
  'account',

  // misc
  'countries',
  'page',
];

/**
 * An array of allowed resolvers manually generated outside of KeystoneJS.
 * Any other manually generated resolvers are not allowed to be executed.
 */
const CUSTOM_RESOLVERS = [
  // account
  'accountPasswordReset',
  'addAndGetOTP',
  'accountSignIn',
  'accountSignInSendNewCode',
  'createAnAccount',
  'deleteAnAccount',
  'getAccountPasswordResetToken',
  'sendEmailConfirmEmailAddress',
  'sendEmailPasswordResetLink',
  'sendEmailReactivateAccountLink',
  'verifyAccountEmailAddress',
  'verifyAccountPasswordResetToken',
  'verifyAccountReactivationToken',
  'verifyAccountSignInCode',

  // application
  'declarationAntiBriberies',
  'declarationConfirmationAndAcknowledgements',
  'declarationHowDataWillBeUseds',
  'deleteApplicationByReferenceNumber',
  'getCompaniesHouseInformation',
  'submitApplication',
  'updateCompanyAndCompanyAddress',

  // feedback
  'createFeedbackAndSendEmail',
];

/**
 * An array of allowed resolvers:
 * - Automatically generated by KeystoneJS
 * - Manually generated by KeystoneJS
 * Any other resolvers are not allowed to be executed.
 */
export const ALLOWED_GRAPHQL_RESOLVERS = [...DEFAULT_RESOLVERS, ...CUSTOM_RESOLVERS];

export default ALLOWED_GRAPHQL_RESOLVERS;
