export const MINIMUM_CHARACTERS = {
  ZERO: 0,
  ONE: 1,
  SORT_CODE: 6,
  ACCOUNT_NUMBER: 6,
  BIC_SWIFT_CODE: 8,
  IBAN: 16,
};

export const MAXIMUM_CHARACTERS = {
  ABOUT_GOODS_OR_SERVICES_DESCRIPTION: 1000,
  ACCOUNT_NUMBER: 8,
  AGENT_NAME: 800,
  AGENT_SERVICE_DESCRIPTION: 1000,
  BIC_SWIFT_CODE: 11,
  BROKER_NAME: 800,
  BUSINESS: {
    GOODS_OR_SERVICES_DESCRIPTION: 1000,
  },
  BUYER: {
    COMPANY_OR_ORGANISATION: 200,
    REGISTRATION_NUMBER: 200,
    PREVIOUS_CREDIT_INSURANCE_COVER: 1000,
  },
  COMPANY_DIFFERENT_TRADING_NAME: 200,
  CONNECTION_WITH_BUYER_DESCRIPTION: 1000,
  CREDIT_PERIOD_WITH_BUYER: 1000,
  DECLINED_BY_PRIVATE_MARKET_DESCRIPTION: 1000,
  EMAIL: 300,
  FEEDBACK: {
    IMPROVEMENT: 1200,
    OTHER_COMMENTS: 1200,
  },
  FULL_ADDRESS: 500,
  IBAN: 34,
  LOSS_PAYEE_NAME: 200,
  PAYMENT_TERMS_DESCRIPTION: 1000,
  PERCENTAGE: 100,
  POLICY_CONTACT_NAME: 400,
  SORT_CODE: 6,
};
