export const COMPANY_DETAILS = {
  PAGE_GREY_HEADING: 'Your business',
  PAGE_TITLE: 'Your company details',
  CRN_HEADING: 'Enter your Companies House registration number (CRN)',
  CRN_HINT: 'For example, 8989898 or SC907816. You\'ll find it on your incorporation certificate or on the Companies House website',
  TRADING_NAME: 'Do you use a different trading name for this company?',
  TRADING_ADDRESS: 'Do you trade from a different address to your registered office address for this company?',
  WEBSITE: 'Enter your company website, if you have one (optional)',
  CONTINUE: 'Continue',
  SAVE_AND_BACK: 'Save and back to all sections',
  TABLE_NAME: 'Your company',
  SEARCH: 'Search',
  NO_COMPANY_HOUSE_NUMER: 'I do not have a UK Companies House registration number',
  YOUR_BUSINESS_HEADING: 'Your business',
};
