name: Codacy Static Code Analysis

on:
  pull_request:

jobs:
  codacy-analysis-cli:
    name: Run Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
