# EXIP Git Hub Actions
#####################################
# This GHA is responsible for initiating linting checks
# across all the directories

name: Quality Assurance - Lint
run-name: Executing lint QA on ${{ github.repository }} 🚀

on:
  pull_request:
    branches: [ main-application ]
    paths:
    - 'src/**'
    - 'e2e-tests/**'
    - 'generate-exip-pricing-grid/**'

env:
  environment: dev
  timezone: 'Europe/London'

jobs:

# 1. Setup test infrastructure
  setup:
    name: Infrastructure setup 🔧
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ env.environment }}
      timezone: ${{ env.timezone }}
    steps:
    - name: Environment 🧪
      run: echo "Environment set to ${{ env.environment }}"
  
    - name: Timezone 🌐
      run: echo "Timezone set to ${{ env.timezone }}"

# 2. Lint
  lint:
    name: Scanning 🎨
    environment:
      name: ${{ needs.setup.outputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Timezone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: ${{ needs.setup.outputs.timezone }}
  
      - name: Repository
        uses: actions/checkout@v3

      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Linting
        working-directory: ./
        run: |
          npm run lint

      - name: Notification
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#exip-github-actions'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()  
