# EXIP Git Hub Actions
#####################################
# This GHA is responsible for initiating linting checks
# across all the directories

name: Quality Assurance - Lint
run-name: Executing lint QA on ${{ github.repository }} 🚀

on:
  pull_request:
    branches: [main, main-*]
    paths:
      - ".github/workflows/lint.yml"
      - "src/**"
      - "e2e-tests/**"
      - "generate-exip-pricing-grid/**"
      - "package*.json"

env:
  environment: "qa"
  timezone: ${{ vars.TIMEZONE }}

jobs:
  # 1. Setup test infrastructure
  setup:
    name: Infrastructure setup 🔧
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ env.environment }}
      timezone: ${{ env.timezone }}
    steps:
      - name: Environment 🧪
        run: echo "Environment set to ${{ env.environment }}"

      - name: Timezone 🌐
        run: echo "Timezone set to ${{ env.timezone }}"

  # 2. Lint
  lint:
    name: Scanning 🎨
    environment:
      name: ${{ needs.setup.outputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Timezone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: ${{ needs.setup.outputs.timezone }}

      - name: Repository
        uses: actions/checkout@v4

      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: ESLint
        working-directory: ./
        run: |
          npm run lint

      - name: Prettier
        working-directory: ./
        run: npm run prettier:all
