# EXIP Git Hub Actions
#####################################
# This GHA is responsible for initiating various test suites
# upon a PR creation, to ensure PR is healthy, bug-free and
# adheres to pre-written unit, API and E2E tests.

name: Quality Assurance - Unit Tests
run-name: Executing test QA on ${{ github.repository }} 🚀

on:
  pull_request:
    branches: [main-application]
    paths:
      - '.github/workflows/test.yml'
      - 'src/**'
      - 'generate-exip-pricing-grid/**'
      - 'package*.json'

env:
  environment: 'qa'
  timezone: 'Europe/London'

jobs:
  # 1. Setup test infrastructure
  setup:
    name: Infrastructure setup 🔧
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ env.environment }}
      timezone: ${{ env.timezone }}
    steps:
      - name: Environment 🧪
        run: echo "Environment set to ${{ env.environment }}"

      - name: Timezone 🌐
        run: echo "Timezone set to ${{ env.timezone }}"

  # 2. UI - Unit test cases
  unit-tests:
    name: Unit 👷
    needs: setup
    environment:
      name: ${{ needs.setup.outputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Timezone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: ${{ needs.setup.outputs.timezone }}

      - name: Repository
        uses: actions/checkout@v3

      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: UI
        working-directory: ./src/ui
        env:
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          BASIC_AUTH_KEY: ${{ secrets.BASIC_AUTH_KEY }}
          BASIC_AUTH_SECRET: ${{ secrets.BASIC_AUTH_SECRET }}
          GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}
          GOV_NOTIFY_EMAIL_RECIPIENT_1: ${{ secrets.GOV_NOTIFY_EMAIL_RECIPIENT_1 }}
          GOV_NOTIFY_EMAIL_RECIPIENT_2: ${{ secrets.GOV_NOTIFY_EMAIL_RECIPIENT_2 }}
          MOCK_ACCOUNT_PASSWORD: ${{ secrets.MOCK_ACCOUNT_PASSWORD }}
        run: |
          npm ci --legacy-peer-deps
          npm run test

      - name: API
        working-directory: ./
        env:
          DATABASE_PORT: ${{ vars.DATABASE_PORT }}
          API_PORT: ${{ vars.API_PORT }}
          UI_PORT: ${{ vars.UI_PORT }}
          API_URL: ${{ secrets.API_URL_LOCAL }}
          API_KEY: ${{ secrets.API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL_LOCAL }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          APIM_MDM_URL: ${{ secrets.APIM_MDM_URL }}
          APIM_MDM_KEY: ${{ secrets.APIM_MDM_KEY }}
          APIM_MDM_VALUE: ${{ secrets.APIM_MDM_VALUE }}
          GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}
          GOV_NOTIFY_API_KEY: ${{ secrets.GOV_NOTIFY_API_KEY }}
          COMPANIES_HOUSE_API_URL: ${{ secrets.COMPANIES_HOUSE_API_URL }}
          COMPANIES_HOUSE_API_KEY: ${{ secrets.COMPANIES_HOUSE_API_KEY }}
          GOV_NOTIFY_EMAIL_RECIPIENT_1: ${{ secrets.GOV_NOTIFY_EMAIL_RECIPIENT_1 }}
          GOV_NOTIFY_EMAIL_RECIPIENT_2: ${{ secrets.GOV_NOTIFY_EMAIL_RECIPIENT_2 }}
          UNDERWRITING_TEAM_EMAIL: ${{ secrets.UNDERWRITING_TEAM_EMAIL }}
          FEEDBACK_EMAIL_RECIPIENT: ${{ secrets.FEEDBACK_EMAIL_RECIPIENT }}
          MOCK_ACCOUNT_PASSWORD: ${{ secrets.MOCK_ACCOUNT_PASSWORD }}
          JWT_SIGNING_KEY: ${{ secrets.JWT_SIGNING_KEY }}
          JWT_VALIDATING_KEY: ${{ secrets.JWT_VALIDATING_KEY }}
        run: |
          docker-compose up --build -d
          npm ci --legacy-peer-deps --prefix ./src/api
          npm run test --prefix ./src/api