import { UKEF_CONTACT_DETAILS } from '../../constants';

export const CONTACT_DETAILS = {
  EMAIL: {
    PREFIX: 'Email',
    TEXT: UKEF_CONTACT_DETAILS.EMAIL.CREDIT_INSURANCE_SUPPORT,
    VALUE: `mailto:${UKEF_CONTACT_DETAILS.EMAIL.CREDIT_INSURANCE_SUPPORT}`,
  },
};
